### PR TITLE
Support systemd socket activation

### PR DESCRIPTION
**Pull request by Ralith**
Makes the service a slightly better citizen. Still needs testing.

### CODE REVIEW

**Comment by Ralith** [comment]
Tested and successfully launches the daemon. However, the daemon then ate a bunch of CPU and worked its way up to 15GB of RAM before I killed it. Is that expected?

**Comment by symphorien** [comment]
the daemon needs to index store paths as they are created. On first run this will takes minutes, even with a fast disk. While indexation is run, the server will return incomplete answers. This means that if nixseparatedebuginfod is systemd activated, it will serve poor results systematically on the first time gdb is run after boot. I don't think this is desirable.

> However, the daemon then ate a bunch of CPU and worked its way up to 15GB of RAM before I killed it. Is that expected?

cpu is expected, not ram usage.

**Comment by Ralith** [comment]
> the daemon needs to index store paths as they are created

Could this be done lazily?

> if nixseparatedebuginfod is systemd activated, it will serve poor results systematically on the first time gdb is run after boot

I don't quite follow; most nix store paths aren't created on boot.

> cpu is expected, not ram usage.

RAM usage was considerable, as described. Any diagnostics I could share?

**Comment by symphorien** [comment]
> Could this be done lazily?

As I said this can take minutes, and I don't want gdb to be blocked for minutes.

> I don't quite follow; most nix store paths aren't created on boot.

Consider the following usage scenario: somebody runs gdb once every month when they encounter a bug worth some time. nixseparatedebuginfod will be started once per month, until next reboot. During a month, thousands of store paths and millions of files (about two mass rebuilds on nixos unstable probably) are created, and on the next time gdb is started, nixseparatedebuginfo has to stat all of these files to find ELF objects and determine their buildid. This takes minutes, and during this time either we block or we answer crappy results (ie: there is no debuginfo available for this buildid, whereas we could download some).

> RAM usage was considerable, as described. Any diagnostics I could share?

build with debuginfo (how ironic that I haven't set separatedDebuginfo = true in my own software) and run it in heaptrack.
if you cannot reproduce because it's related to indexation which has most to do on first startup, remove ~/.cache/nixseparatedebuginfod

**Comment by Ralith** [comment]
> As I said this can take minutes

I mean, is there a way to only (or preferentially) index store paths that are immediately relevant to connected gdb sessions? gdb should already know which files it's looking at, after all. I guess the protocol poses a barrier here?

Longer term I wonder if the index could be generated by nixpkgs builds or maybe hydra directly, so at least only uncached packages would need to be locally indexed.

> run it in heaptrack

Can't seem to reproduce anymore, even with an empty cache. Maybe something specific to running as a service; haven't had time to try that variable. Or maybe I just misread something?

**Comment by symphorien** [comment]
> I mean, is there a way to only (or preferentially) index store paths that are immediately relevant to connected gdb sessions? gdb should already know which files it's looking at, after all. I guess the protocol poses a barrier here?

The protocol is described here: https://www.mankier.com/8/debuginfod#Webapi
the only input is the buildid, and I need a store path. the only way I could think of is to watch the sqlite db of nix to know when new store path appear, and open all files, determine their buildid, and record the buildid -> store path association.

> Longer term I wonder if the index could be generated by nixpkgs builds or maybe hydra directly, so at least only uncached packages would need to be locally indexed.

hydra already does so, but in a way that only allows retrieving debug symbols, not source (it's what dwarffs uses).

but to be honest, with the current situation where nixseparatedebuginfod starts on boot, indexation should never take time, so I'm not sure if it's a pressing problem.

**Pull request closed without merging**
