### PR TITLE
improve request to source path candidate matching

### PR DESCRIPTION
**Pull request by pjungkamp**
The debuginfo line information specifies the source path as `/build/source/path/to/source` while the path that is matched against is only `path/to/source` relative to the downloaded sources.

The current algorithm for finding the best source file candidates for a requested file path does not seem to work for me.
A requested target path is matched by going `root-to-basename` through target, matching it against the source path.
Since the source path does not have the `/build/source` prefix the matching is immediatly aborted and two files of the same name in different subdirectories of the source can never be correctly disambiguated.

Since I don't know whether the `/build/source` prefix is guaranteed, I opted to fix this by reversing the matching direction to compare from `basename-to-root` instead, finding the longest matching suffix in the path components. This seems to work nicely.

### CODE REVIEW

**Comment by symphorien** [comment]
Thank you for your PR.

Rereading the original algorithm, it looks bottom to top to me as you want, so the difference between the old one and the one you propose is not obvious to me.

Do you think as a first step you could write a regression test that creates a dummy folder structure and runs the selection algorithm ? I think it would be easier for me to review the improvement you propose by seeing a concrete case where the old selection algorithm fails.

**Comment by pjungkamp** [comment]
The current algorithm indeed tries to go from basename to root through the path. My comment above misrepresented the old algorithm. I'm sorry for the confusion.

I'll explain the problem on the path query that initially led me to writing this patch after I debugged a query using `lldb`.

I was debugging an application using the `libwebsockets` library. I tried to step into the `lib/core-net/network.c` file of the repository, where `nixseparatedebuginfod` reported that there were multiple results which couldn't be disambiguated.

The two ambiguous sources were:
- `lib/core-net/network.c`
- `lib/plat/optee/network.c`

The path contained in the debuginfo was `/build/source/lib/core-net/network.c`, seemingly unambiguous.

The current algorithm sets `i` to the length of the target path -1 to access the last element of the path.
It then searches for all files matching the basename of the target path.
If multiple files with the same basename are present the last section of the function starts the disambiguation.
The source path are returned from the `member_path` method on a candidate, which is relative to the root of the fetched source.
Here lies the problem.

The current algorithm indexes both the target path and the source path using the same i.
Since the target path has length `5` i is initialized to `4` and the first index checked by the algorithm is `3`.
`target_path[3]` is `core-net`. `candidate_path.get(3)` is `None` or `Some("network.c")`, both equally wrong, thus ambiguous.
The solution could be another index attached to each source path to accurately traverse it back to front.

I instead opted to rewrite the algorithm using iterators, saving some copies in the process.

**Comment by symphorien** [comment]
Thank you for your explanation. I added a regression test about the case you describe, and to my great surprise it passes with the current version of the code. Could you check that correctly translated your issue into this test?

https://github.com/symphorien/nixseparatedebuginfod/commit/c47b900ec80733701bfd11f8c65daabead702938#diff-41a991785a2eba02345db5fdcbf15b660f27b2841b8f61a084a7db66e69bf3eeR522-R532

**Comment by pjungkamp** [comment]
Weird! I'll try to replicate my initial issue and add traces all throughout the current algorithm.

If I can reproduce I'll add a log and diff.

**Comment by pjungkamp** [comment]
First off, I can still reproduce on current `master`.

Here's the output from an unmodified instance.
```
2023-06-19T07:08:11.279866Z  INFO nixseparatedebuginfod::index: Done indexing new store paths
2023-06-19T07:08:11.293519Z  INFO request{method=GET uri=/buildid/9880df89ab5ef7047905294a46a68947ebff6eb7/source/build/source/lib/core-net/network.c version=HTTP/1.1}: nixseparatedebuginfod::server: Responding error 404 Not Found: looking in source: cannot tell {(0, ["/", "nix", "store", "znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source", "lib", "plat", "optee", "network.c"]), (1, ["/", "nix", "store", "znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source", "lib", "core-net", "network.c"])} apart from /nix/store/znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source for target build/source/lib/core-net/network.c
2023-06-19T07:08:11.293733Z DEBUG request{method=GET uri=/buildid/9880df89ab5ef7047905294a46a68947ebff6eb7/source/build/source/lib/core-net/network.c version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=97 ms status=404
```

**Comment by pjungkamp** [comment]
Here is some more verbose logging output:
```log
2023-06-19T08:04:38.206546Z DEBUG request{method=GET uri=/buildid/9880df89ab5ef7047905294a46a68947ebff6eb7/source/build/source/lib/core-net/network.c version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2023-06-19T08:04:38.216662Z  WARN nixseparatedebuginfod::store: found candidates [File("/nix/store/znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source/lib/plat/optee/network.c"), File("/nix/store/znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source/lib/core-net/network.c")] for target build/source/lib/core-net/network.c in /nix/store/znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source
2023-06-19T08:04:38.216813Z  WARN nixseparatedebuginfod::store: comparing Some("znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source") in member to Some("core-net") in target
2023-06-19T08:04:38.216838Z  WARN nixseparatedebuginfod::store: comparing Some("znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source") in member to Some("core-net") in target
2023-06-19T08:04:38.216853Z  WARN nixseparatedebuginfod::store: remaining candidates {}
2023-06-19T08:04:38.217273Z  INFO request{method=GET uri=/buildid/9880df89ab5ef7047905294a46a68947ebff6eb7/source/build/source/lib/core-net/network.c version=HTTP/1.1}: nixseparatedebuginfod::server: Responding error 404 Not Found: looking in source: cannot tell {(1, ["/", "nix", "store", "znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source", "lib", "core-net", "network.c"]), (0, ["/", "nix", "store", "znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source", "lib", "plat", "optee", "network.c"])} apart from /nix/store/znvzgbqiw7wz28cl4w7bwz5b0j64w90i-source for target build/source/lib/core-net/network.c
```

Here's the diff introducing the logging:
```diff
diff --git a/src/store.rs b/src/store.rs
index 66ec98b..07ff5f1 100644
--- a/src/store.rs
+++ b/src/store.rs
@@ -469,6 +469,12 @@ pub fn get_file_for_source(
     if candidates.len() == 1 {
         return Ok(Some(candidates[0].clone()));
     }
+    tracing::warn!(
+        "found candidates {:?} for target {} in {}",
+        &candidates,
+        request.display(),
+        &source.display(),
+    );
     let candidates_split: HashSet<(usize, Vec<&OsStr>)> = candidates
         .iter()
         .map(|p| p.member_path().iter().collect())
@@ -480,8 +486,16 @@ pub fn get_file_for_source(
         let next: HashSet<&(usize, Vec<&OsStr>)> = candidates_ref
             .iter()
             .cloned()
-            .filter(|&(_, ref c)| c.get(i) == target.get(i))
+            .filter(|&(_, ref c)| {
+                tracing::warn!(
+                    "comparing {:?} in member to {:?} in target",
+                    c.get(i).copied().map(OsStr::to_string_lossy),
+                    target.get(i).copied().map(OsStr::to_string_lossy),
+                );
+                c.get(i) == target.get(i)
+            })
             .collect();
+        tracing::warn!("remaining candidates {:?}", next);
         if next.len() == 0 {
             anyhow::bail!(
                 "cannot tell {:?} apart from {} for target {}",
```

**Comment by pjungkamp** [comment]
I also adapted the test to show the failure, check out [this](https://github.com/PJungkamp/nixseparatedebuginfod/tree/show-candidate-error) branch for the reproducer!

**Comment by pjungkamp** [comment]
I'd argue my iterator algorithm fixes this problem, is probably cleaner than indexing, and does less allocations.

Thank you very much for this awesome tool, seeing it work is always magical!

**Comment by symphorien** [comment]
Thank you for the reproducer, I could understand the issue and fix it in #9.

I prefer the existing path matching algorithm to your approach of finding the file with the largest number of unordered common component because it would favor store/store/foo/bar to good/baz/store/bar to match /build/store/bar if I understand correctly. I prefer something reliable with as few false positives as possible to something fuzzier with less false negatives.

Could you test #9 to see if it fixes your original problem?

**Comment by pjungkamp** [comment]
What I did not like about the eliminating algorithm (besides the broken index) is the HashSet of all candidates constructed in each loop iteration.

The proposed algorithm is pretty straight forward.
Let's take your example:

- Candidates: "store/store/foo/bar" and "good/baz/store/bar"
- Target: "/build/store/bar"

What it does for each candidate:
1. split the candidates into component iterators. E.g. ["store" "store" "foo" "bar"] and ["good" "baz" "store" "bar"]
2. reverse the candidate iterators and the target iterator.
3. zip target and candidate components together. E.g. [("bar","bar") ("foo","store") ("store","build")] and [("bar","bar") ("store","store") ("baz","build")]
4. find the matching length by the position of the first mismatch. E.g. `matching_len = 1` and `matching_len = 2`

It then adjusts the vector of best candidates according to the results.
Since the `matching_len` for "good/baz/store/bar" was greater, it's preferred.

The commit I just introduced also tracks the length of the matching candidates and prefers shorter ones.
This disambiguates "a/b/c/path/to/file" and "a/b/path/to/file" for a target "build/source/path/to/file".

I can of course also replace the `fold` with a `for`-loop and move the state to local variables if you are more comfortable with that.

**Comment by symphorien** [comment]
Ah ok I understand better, then indeed your contribution is better.

> I can of course also replace the fold with a for-loop and move the state to local variables if you are more comfortable with that.

Yes I would prefer a for loop, that seems easier to read.

Do you mind taking the regression tests from #9 as well?

**Comment by pjungkamp** [comment]
> Do you mind taking the regression tests from #9 as well?

Of course.

**Comment by pjungkamp** [comment]
I rebased onto current master and picked up the regression tests. Unit tests are passing. The integration takes its time...

**Comment by pjungkamp** [comment]
I reauthored the test commit as I didn't want to create commit message in your name.

**Comment by symphorien** [comment]
Thank you.

**Pull request merged**
